import os

""" DATASET HYPERPARAMETERS """
IMG_WIDTH = 1024
IMG_HEIGHT = 576
PATCH_WIDTH = 720
PATCH_HEIGHT = 260
CHANNELS = 1 # 1 for greyscale, 3 for color
NUM_DATA_BATCHES = 1
BATCH_SIZE = 32

NUM_DIMS = 2
NUM_POINTS = 4
AUGMENT = True
NUM_CLASSES = NUM_DIMS * NUM_POINTS

""" DIRECTORIES """
DROPBOX_LOCATION = os.path.join('data')
CHECKPOINT_DIR = os.path.join('checkpoint')

""" MODEL INPUT """
MODEL_SCALER = 0.5
MODEL_WIDTH = int(PATCH_WIDTH * MODEL_SCALER)
MODEL_HEIGHT = int(PATCH_HEIGHT * MODEL_SCALER)
